name: 打包 Debian 包

on: [workflow_dispatch]

jobs:
  build:
    name: 构建 Debian 包
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: 编译
        run: cargo build --release
      - name: 安装 cargo-deb
        run: cargo install cargo-deb
      - name: 打包 Debian 包
        run: cargo deb --build
      - name: 上传
        uses: actions/upload-artifact@v4.6.2
        with:
          name: rt-linux
          path: |
            target/debian/*.deb
