name: 发行

on:
  workflow_dispatch:
    inputs:
      rname:
        description: "发行版名称"
        type: string
      tag_name:
        description: "标签名称"
        type: string

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:

  linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: 编译
      run: cargo build --release
    - name: 移动脚本
      run: |
        cp install.sh target/release/install.sh
        cp uninstall.sh target/release/uninstall.sh
        chmod +x target/release/install.sh
        chmod +x target/release/uninstall.sh
    - name: 上传
      uses: actions/upload-artifact@v4.6.2
      with:
        name: rt-linux
        path: |
          target/release/rt
          target/release/locales
          target/release/install.sh
          target/release/uninstall.sh

  windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: 编译
      run: cargo build --release
    - name: 上传
      uses: actions/upload-artifact@v4.6.2
      with:
        name: rt-windows
        path: |
          target/release/rt.exe
          target/release/locales

  release:
    name: 发行
    needs: [linux, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 下载文件
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: 重新压缩(Linux)
        run: |
          cd rt-linux && zip -r "../rt-linux.zip" .
    
      - name: 重新压缩(Windows)
        run: |
          cd rt-windows && zip -r "../rt-windows.zip" .


      - name: 自动发布发行版
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.rname }}
          tag_name: ${{ inputs.tag_name }}
          draft: false
          make_latest: true
          files: |
            rt-linux.zip
            rt-windows.zip