name: Win7 测试

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  x64:
    name: x64
    runs-on: windows-latest

    steps:
      - name: 仓库初始化
        uses: actions/checkout@v3

      #- name: 安装 LLVM
      #  uses: ZhongRuoyu/setup-llvm@v0
      #  with:
      #    llvm-version: 17

      - name: 安装 Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc

      - name: 编译
        run: |
          cargo build --release -Z build-std --target x86_64-win7-windows-msvc

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: riptree-x64-win7
          path: |
            target\x86_64-win7-windows-msvc\release\locales
            target\x86_64-win7-windows-msvc\release\rt.exe
            target\x86_64-win7-windows-msvc\release\rt.pdb
